navbar
PranavBarthwal/cosmoXplore pull request #170
Opened 2024-05-15 19:08 UTC by kairveeehh

# Title of Issue and Pull Request must be Same
 ui fixed of the navbar added hover effects as well 
## Issue number 
#60 
eg : Fixes #4 -->

Fixes #60 

## Video/Screenshots (mandatory)
![Screenshot 2024-05-16 003428](https://github.com/PranavBarthwal/cosmoXplore/assets/145572028/e44cd2ac-b3e3-4cf9-93a0-3076730bbaa3)
![Screenshot 2024-05-16 003421](https://github.com/PranavBarthwal/cosmoXplore/assets/145572028/ad1eb0fb-e953-4951-88b1-35b9f7d7dcd3)

## Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have gone through the  `contributing.md` file before contributing

## Additional context:
@PranavBarthwal ## please review and merge the PR

2024-05-16 15:10 UTC, PranavBarthwal requested changes
Can you reduce the padding between buttons and add that glowing only on hover.
Also can you change that glowing color to purple, same as that of hero image.

2024-05-16 15:12 UTC, kairveeehh commented
> Can you reduce the padding between buttons and add that glowing only on hover.
> Also can you change that glowing color to purple, same as that of hero image.

The glowing effect is only on hover , I'll reduce the padding between buttons( margins) and set glowing color to.purple

2024-05-16 15:29 UTC, kairveeehh commented
@PranavBarthwal  i have made these changes 
reducing more padding will lead to cross each other's hover so I have kept it minimum possible 
@PranavBarthwal 
## please review and merge my PR
![Screenshot 2024-05-16 205526](https://github.com/PranavBarthwal/cosmoXplore/assets/145572028/833df82a-0824-401c-aa69-015357929fa7)

2024-05-17 07:07 UTC, kairveeehh commented
any updates @PranavBarthwal ?

2024-05-22 15:06 UTC, kairveeehh commented
Please update me it's been over a week @PranavBarthwal

2024-05-22 15:50 UTC, PranavBarthwal commented
We are migrating this project to react. It'll take a day or two before we start merging all the PRs.

2024-05-29 13:56 UTC, kairveeehh commented
@PranavBarthwal  its been weeks now , please let me know and dont let my efforts go in waste

2025-05-27 07:19 UTC, closed without merging